version: '3'

services:
  # --- NEU: Der Webserver für Sulu ---
  php:
    image: sulu/sulu-demo:php8.2
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      # Verweist auf den Service-Namen "database" unten
      DATABASE_URL: "mysql://root:ChangeMe@database:3306/su_myapp?serverVersion=8.4"
    depends_on:
      - database

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.4}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-su_myapp}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - database_data:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

volumes:
  database_data:
